# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pn6YQxsmKRcDcQ8edjFXJtxmPL7RAHiC
"""

pip install pytelegrambotapi

import wikipedia as wiki
import telebot


bot = telebot.TeleBot('6887141702:AAEBJT2VLoK76k1z0IvRNjHxkAFeLfBzJyA')

first_button = telebot.types.InlineKeyboardButton('کانال من', url='https://t.me/test_bot126')
second_button = telebot.types.InlineKeyboardButton('سلام', callback_data="سلام")
markup = telebot.types.InlineKeyboardMarkup(row_width=1)
markup.add(first_button, second_button)

#allert clik 'سلام' button
@bot.callback_query_handler(func=lambda call:True)
def callback(call):
  bot.answer_callback_query(call.id, 'سلام', show_alert=True)
#keyboard button
key_markup = telebot.types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
key_markup.add('ویکی پدیا', 'کانال من', 'سازنده', 'ثبت نام')
#start command
@bot.message_handler(commands=['start'])
def send_welcome(message):
  bot.send_message(message.chat.id, "hi /wikipedia :ویکی پدیا", reply_markup=markup)
#help command
@bot.message_handler(commands=['wikipedia'])
def help_me(message):
  bot.reply_to(message, "سوال خود را وارد کنید")
  bot.register_next_step_handler(msg, bb)
#keyboard button
@bot.message_handler()
def keyboard(message):
  if message.text == 'ویکی پدیا':
    msg = bot.send_message(message.chat.id, "سوال خود را وارد کنید")
    bot.register_next_step_handler(msg, bb)
  elif message.text == 'سازنده':
    bot.send_message(message.chat.id, "ارتین صیدی")
  elif message.text == 'کانال من':
    bot.send_message(message.chat.id, "https://t.me/test_bot126")

def bb(message):
  cc = message.text
  print(cc)
  keyword = cc
  LANG = 'fa'
  wiki.set_lang(LANG)
  summrey = wiki.summary(keyword , sentences =4)
  print(summrey)
  bot.send_message(message.chat.id, summrey)


bot.infinity_polling()